import Link from 'next/link'
import Head from 'next/head'
import NavBar from '../../Components/NavBar/NavBar'
export const getServerSideProps =async ()=>{
    const res = await fetch('https://pokeapi.co/api/v2/type')
    const data = await res.json()
    return{
        props :{pokemons : data}
    }

    
}


const types=({pokemons})=>{
    return(
        <div>
            <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"></link>
      </Head>
            <NavBar/>
            <br />
            <div className="typeheading">
  <h2> Pokemon Types</h2>
</div>
        
        {
            pokemons.results.map((pokemontype)=>{
                return (
               // eslint-disable-next-line react/jsx-key
               <div>
                   <div className="list-group" style={{padding:"1px"}}>
  
  <Link href={"/types/"+pokemontype.name}><a  className="list-group-item list-group-item-action" >{pokemontype.name.toUpperCase()}</a></Link>

</div>
                   
               
               </div>
                

                )
                

            })
            
        }


        </div>
    )

}

export default types
