import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../Components/NavBar/NavBar'
import styles from '../styles/Home.module.css'
import Marquee from "react-fast-marquee";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"></link>
      </Head>

      
      
      
      <NavBar/>
      <nav aria-label="breadcrumb">
  <ol  className="breadcrumb">
    <div className="welcome">
 <h5 > <Marquee>!!...Welcome to Pokedex... A World of Pokemons...!!</Marquee></h5>
  </div>
  </ol>
</nav>

    </div>
  )
}
