import Image from 'next/image'

import NavBar from '../../Components/NavBar/NavBar'
import Head from 'next/head';
import Link from 'next/link'
import { motion } from "framer-motion"


const PokemonPage = ({name,pokemon,error})=>{

 

    return error ?
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"></link>
      </Head>
      <NavBar/>
      <br />
    <div className="detailscard">
        <div className="detailspokemonname">
          
          
          <h3 className="detailspokemonname">Sorry No Pokemon with this name</h3>
          
        <Link href="/"><a>  <h6 className="detailspokemonname" style={{textDecoration: "underline"}}> Go Back to Home</h6></a></Link>
          </div>
          </div>
          </div>:
    
    
    <motion.div
    
    >
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"></link>
      </Head>
    <NavBar/>  
    <br />
    
    
    <motion.div className="detailscard" initial={{x:'-100vw'}}
    animate={{x:0}}
    transition={{delay:0.001}}>
        <div className="detailspokemonname">
          <h3 className="detailspokemonname">{pokemon.name.toUpperCase()}</h3>
          </div>
        
        {
          pokemon.types.map((type)=>{
            return (
              <div className="detailstype" key="type.type.name">
            <Link href={"/types/"+type.type.name}><a>  <span className="badge badge-success detailstype">{type.type.name.toUpperCase()}</span></a></Link>
              </div>
            )
          })
        }

        
        <div className="detailsimage">
        <img className="detailsimage" src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon.id}.png`} />
        </div>

        <div className="detailsabout">
        <button  className="btn btn-success">About</button>
<ul className="list-group">
        <li className="list-group-item list-group-item-success">Height : {pokemon.height}0cm</li>
        <li className="list-group-item list-group-item-success">Weight : {pokemon.weight}Kg</li>
        <li className="list-group-item list-group-item-success">Abilities : {
          pokemon.abilities.map((ability)=>{
            return(
              <div key={ability.ability.name}><ul><li>{ability.ability.name.toUpperCase() }</li></ul></div>
            )
          })
        }</li>
        
        </ul>

        
  
         
       

        </div>
      

         
        
    
    </motion.div>


        

    </motion.div>  

};


PokemonPage.getInitialProps=({query})=>{

  
     return fetch(`https://pokeapi.co/api/v2/pokemon/${query?.pokemon}`)
                .then((resp)=>resp.json())
                .then(data=>{
                  console.log(query.pokemon)

                  return {name: query.pokemon,pokemon: data}

                }).catch((err)=>{

                  return{error : err}
                })




           
}

export default PokemonPage;